### ISSUE TITLE
Interaction net reduction visualization

### ISSUE THREAD

**Issue by cwgoes** [anoma/research#6]
This will be very helpful to ensure we've implemented everything correctly, increase our intuitional grasp on the system, and produce attractive visualizations.

- Convert an interaction net graph into a PNG or SVG, placing the nodes / wires automatically
- Reduce an interaction net and generate an image for each step, arrange in sequence (easy)

In the future we could possibly make it interactive (step backwards / forwards in time) or allow the user to reposition the nodes but that sounds like overkill for now.

cc @mariari

**Comment by mariari** [comment]
Currently a direct translation from the FGL library to graphs is included. This is just a temporary measure to better test the current implementation

## Current Issues
1. The images generated are all shaped as circles
2. Orientation is not clear in the current model
3. Stepping is not currently done


In the current model only 3 is solveable, but effort should be spent pursuing a proper solution.

**Comment by cwgoes** [comment]
As discussed (awhile ago, forgot to write down then), we should:

- Export the reduction steps as JSON & render in JS / web browser (eventually we might also implement reduction itself in JS, in which case we could only export the term)
- Highlight primary pairs, color node types or otherwise clearly disambiguate
- Render a three-dimensional interaction net (x, y dimension - graph, z dimension - level in EAL) with a slider to progress backwards & forwards in time (reduction steps), zoom, etc.
  [3d-force-graph](https://github.com/vasturiano/3d-force-graph) or [Three.js](https://threejs.org/) (which 3d-force-graph just wraps) might be suitable libraries.
