### ISSUE TITLE
Pick a strategy for deriving induction

### ISSUE THREAD

**Issue by cwgoes** [anoma/research#7]
QTT does not natively support induction derivation; we need to add typing rules for it.

Some options are:
- Add primitive datatypes (e.g. Nat) with elimination rules which can be used for induction
  This is what @thealmarty has implemented in LambdaPi.
- Allow custom induction definitions a la the [Calculus of Inductive Constructions](https://hal.inria.fr/hal-01094195/document).
  This is pretty similar to primitive datatypes; they go into more detail w.r.t. how to allow user-defined types to derive induction.
- In line with Aaron Stump's work on Cedille, add a few type primitives (implicit product, dependent intersection, equality type), which allows induction to be derived for lambda-encoded naturals (and possibly other lambda-encoded datatypes)
  [Here](https://homepage.cs.uiowa.edu/~astump/papers/from-realizability-to-induction-aaron-stump.pdf) is the latest paper I know about on the topic. [Here](https://homepage.cs.uiowa.edu/~astump/papers/cedille-draft.pdf) is the longer (earlier) paper on Cedille.

There may be other options. The first few chapters of the Cedille paper survey some prior research.

**Comment by cwgoes** [comment]
...specifically, we might want the ability to derive induction for [Mogensen-Scott-encoded datatypes](https://en.wikipedia.org/wiki/Mogensen%E2%80%93Scott_encoding).

[Here](https://www.nlda-tw.nl/janmartin/papers/jmjansenLambdapaper.pdf) is another paper on that encoding, and [here](http://lucacardelli.name/Papers/Notes/scott2.pdf) is a note on typing them. [Here](https://fermat.github.io/document/papers/scott-dep.pdf) is a typing-relevant discussion by Fu & Stump. I think Scott encodings have bad space efficiency for large recursive types (e.g. Nats, Lists); might want to use [Boehm-Berarducci encoding](http://okmij.org/ftp/tagless-final/course/Boehm-Berarducci.html) in some cases.

Likely we will need some primitive types (w/induction) anyways; but the more we can do in lambda-encoded data the better I think (and maybe we can just optimize particular lambda-encoded patterns with types, e.g. natural numbers, to machine representations at a lower level).

**Comment by mariari** [comment]
[Here](https://arxiv.org/abs/1803.02473v1) is a paper by Aaron Stump outlining Efficient Mendler-Style Lambda encodings in Cedile.

Stump also explains deriving induction for Mendler style lambda encodings in two Cedile cast videos which can be found [here (p1)](https://www.youtube.com/watch?v=HqvBBf_cjDo) and [here (p2)](https://www.youtube.com/watch?v=-iB2Cup7cwQ) 

This may be a useful representation, however I'd need to research more on it to compare it with boehm berducci encoding (typed church encoding) and Morgensen Scott encodings

**Comment by mariari** [comment]
# Comparison of various induction strategies

## Church / Boehm Berducci
- Is a catamorphism
- Doing any pattern matching needs to be at least O(n)
  + See Pred for natural numbers (Parigot) or the [deconstruction mechanism](https://github.com/mariari/Misc-ML-Scripts/blob/master/OCaml/nameless-boehm-beraducci.ml#L28) for general recursion
- For non Infinite data, termination is guaranteed
- Typable in System F 
## Parigot encoding
- Typeable in System F
- positive recursive type
- Pred is O(1) 
- Representation is exponential on data O(2^n)
  + so exponential on n where n is a natural number!
## Stump-Fu encoding
- improvement on Parigot encoding only taking up O(n^2) space
## Mendler Style 
- Linear space O(n) for data
- O(1) pred function
- Termination of positive and negative inductive datatypes is proven given a few invariants
  + This negative inductive datatypes termination may not be true in the modification made by stump
  + The previous research[1] that had negative inductive datatypes being proven to terminate had O(n) Pred
- Strong induction on negative inductive types is a problem
  + Open research question

## Morgensen-Scott Encoding
- Only works for Positive inductive types
- O(1) Pred
- [Typeable in System F(?)](https://cstheory.stackexchange.com/questions/43816/termination-checking-for-scott-encodings-in-system-f-with-positive-recursive-typ)
- Termination can not be established (?) (see link above!)


[1] A Hierarchy of Mendler style Recursion Combinators

**Comment by cwgoes** [comment]
Another note: we will need the ability to totality-check functions, otherwise the type system can be trivially bypassed - if we can identify particular encodings which we know will halt, though, that's fine.

**Comment by cwgoes** [comment]
The continuation-based encoding proposed [here](https://gist.github.com/zmactep/c5e167c86fb8d80dcd5532792371863f) is interesting.

**Comment by cwgoes** [comment]
Are there particularly likely use-cases for negative inductive datatypes in practice?

**Comment by cwgoes** [comment]
For linked lists or trees, we definitely need linear space, and the constant factor matters too.

Definite requirements
- O(1) pattern matching (pred)
- O(n) space for data (naturals, linked lists, trees) with low or optimizable constant factor
- Termination checking on positive inductive datatypes
- Induction on positive inductive datatypes (a few Aaron Stump type theory additions are OK)
- Typeable in dependent type theory

Nice to have
- Termination / induction on negative inductive datatypes
- Typeable in simpler type theory

Given that, it seems like Mendler and Mogensen-Scott are the two most likely candidates, plus perhaps the continuation encoding if we can type it etc.

Of course, we can choose different encodings for different datatypes on a case-by-case basis as well.
